### PR TITLE
Reference: https://github.com/golang-module/carbon/pull/134#issuecomm…

### PR DESCRIPTION
**Pull request by DrOctavius**
#134 

Adapted function "ToLayoutString" -> requires some code review and output testing!

```
log.Println(carbon.Now().SetLocale("en").Layout("02 January 2006"))
log.Println(carbon.Now().SetLocale("ro").Layout("02 January 2006"))
log.Println(carbon.Now().SetLocale("ru").Layout("02 January 2006"))
log.Println(carbon.Now().SetLocale("zh-CN").Layout("02 January 2006"))
```

```
The expected Output should be:
21 May 2022
21 Mai 2022
21 Май 2022
21 五月 2022
```

### CODE REVIEW

**Review by gouguoyin — COMMENTED** [review]
I think it is also necessary to consider that words starting with the escape symbol "\\" don't need to be replaced, such as 

```go
carbon.Now().SetLocale("zh-CN").Layout("\\January is January") // January is 五月
```

**Comment by DrOctavius** [comment]
Yes, totally agree! i just wrote an algo! please test & review it! thanks!

**Comment by DrOctavius** [comment]
Hey @gouguoyin, how are you? did you had some time to review? thanks!

**Comment by gouguoyin** [comment]
> Hey @gouguoyin, how are you? did you had some time to review? thanks!

Thanks for your contribution, as the code changes are quite large, I'm reviewing and thinking if there is a more elegant way.

**Pull request closed without merging**
