### PR TITLE
chore: use String() instead of fmt.Sprintf

### PR DESCRIPTION
**Pull request by testwill**

### CODE REVIEW

**Comment by open-git** [comment]
What is the difference?

**Comment by gouguoyin** [comment]
What is the difference?

**Comment by testwill** [comment]
[should use String() instead of fmt.Sprintf (megacheck)](https://github.com/golangci/golangci-lint/issues/160)
you can use obj.String() instead of fmt.Sprintf("%s", obj) because fmt.Sprintf calls obj.String() internally

**Comment by gouguoyin** [comment]
Intentionally using `fmt.Sprintf()` to test the scenario of forcing the `c.Lunar()` struct to be output as string

**Pull request closed without merging**
